/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as AgendamentoTokenRouteImport } from './routes/agendamento.$token'
import { Route as AgendarSucessoTokenRouteImport } from './routes/agendar.sucesso.$token'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)
const AgendamentoTokenRoute = AgendamentoTokenRouteImport.update({
  id: '/agendamento/$token',
  path: '/agendamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSucessoTokenRoute = AgendarSucessoTokenRouteImport.update({
  id: '/sucesso/$token',
  path: '/sucesso/$token',
  getParentRoute: () => AgendarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/agendar/sucesso/$token': typeof AgendarSucessoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/agendar/sucesso/$token': typeof AgendarSucessoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agendamento/$token': typeof AgendamentoTokenRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/agendar/sucesso/$token': typeof AgendarSucessoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/servicos'
    | '/agendamento/$token'
    | '/clientes/$id'
    | '/agendar/sucesso/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/servicos'
    | '/agendamento/$token'
    | '/clientes/$id'
    | '/agendar/sucesso/$token'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agendar'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/login'
    | '/servicos'
    | '/agendamento/$token'
    | '/clientes/$id'
    | '/agendar/sucesso/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgendarRoute: typeof AgendarRouteWithChildren
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ServicosRoute: typeof ServicosRoute
  AgendamentoTokenRoute: typeof AgendamentoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/agendamento/$token': {
      id: '/agendamento/$token'
      path: '/agendamento/$token'
      fullPath: '/agendamento/$token'
      preLoaderRoute: typeof AgendamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/sucesso/$token': {
      id: '/agendar/sucesso/$token'
      path: '/sucesso/$token'
      fullPath: '/agendar/sucesso/$token'
      preLoaderRoute: typeof AgendarSucessoTokenRouteImport
      parentRoute: typeof AgendarRoute
    }
  }
}

interface AgendarRouteChildren {
  AgendarSucessoTokenRoute: typeof AgendarSucessoTokenRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarSucessoTokenRoute: AgendarSucessoTokenRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgendarRoute: AgendarRouteWithChildren,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ServicosRoute: ServicosRoute,
  AgendamentoTokenRoute: AgendamentoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
